project_name: ttnbridge

release:
  github:
    owner: ripienaar
    name: ttnbridge
  name_template: "Release {{.Tag}}"
  draft: true

changelog:
  skip: true

builds:
  - main: main.go
    id: ttnbridge
    binary: ttnbridge
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    format: zip
    files:
      - README.md
      - LICENSE

dockers:
  - goos: linux
    goarch: amd64
    skip_push: true
    binaries:
      - ttnbridge
    image_templates:
      - "ripienaar/ttnbridge:latest"
      - "ripienaar/ttnbridge:{{.Version}}"

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256
